// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClusterConfig.proto

package com.spectralogic.escapepod.cluster.models;

public final class ClusterConfigProto {
  private ClusterConfigProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClusterConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.spectralogic.escapepod.cluster.models.ClusterConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string nodeId = 2;</code>
     */
    java.lang.String getNodeId();
    /**
     * <code>string nodeId = 2;</code>
     */
    com.google.protobuf.ByteString
        getNodeIdBytes();

    /**
     * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
     */
    java.util.List<com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode> 
        getNodesList();
    /**
     * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
     */
    com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode getNodes(int index);
    /**
     * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
     */
    int getNodesCount();
    /**
     * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
     */
    java.util.List<? extends com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNodeOrBuilder> 
        getNodesOrBuilderList();
    /**
     * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
     */
    com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNodeOrBuilder getNodesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.spectralogic.escapepod.cluster.models.ClusterConfig}
   */
  public  static final class ClusterConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.spectralogic.escapepod.cluster.models.ClusterConfig)
      ClusterConfigOrBuilder {
    // Use ClusterConfig.newBuilder() to construct.
    private ClusterConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClusterConfig() {
      name_ = "";
      nodeId_ = "";
      nodes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ClusterConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nodeId_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                nodes_ = new java.util.ArrayList<com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode>();
                mutable_bitField0_ |= 0x00000004;
              }
              nodes_.add(
                  input.readMessage(com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          nodes_ = java.util.Collections.unmodifiableList(nodes_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spectralogic.escapepod.cluster.models.ClusterConfigProto.internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spectralogic.escapepod.cluster.models.ClusterConfigProto.internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.class, com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.Builder.class);
    }

    public interface ClusterNodeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.com.spectralogic.escapepod.cluster.models.URL host = 1;</code>
       */
      boolean hasHost();
      /**
       * <code>.com.spectralogic.escapepod.cluster.models.URL host = 1;</code>
       */
      com.spectralogic.escapepod.cluster.models.Url.URL getHost();
      /**
       * <code>.com.spectralogic.escapepod.cluster.models.URL host = 1;</code>
       */
      com.spectralogic.escapepod.cluster.models.Url.URLOrBuilder getHostOrBuilder();
    }
    /**
     * Protobuf type {@code com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode}
     */
    public  static final class ClusterNode extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode)
        ClusterNodeOrBuilder {
      // Use ClusterNode.newBuilder() to construct.
      private ClusterNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ClusterNode() {
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private ClusterNode(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.spectralogic.escapepod.cluster.models.Url.URL.Builder subBuilder = null;
                if (host_ != null) {
                  subBuilder = host_.toBuilder();
                }
                host_ = input.readMessage(com.spectralogic.escapepod.cluster.models.Url.URL.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(host_);
                  host_ = subBuilder.buildPartial();
                }

                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.spectralogic.escapepod.cluster.models.ClusterConfigProto.internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_ClusterNode_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.spectralogic.escapepod.cluster.models.ClusterConfigProto.internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_ClusterNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.class, com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.Builder.class);
      }

      public static final int HOST_FIELD_NUMBER = 1;
      private com.spectralogic.escapepod.cluster.models.Url.URL host_;
      /**
       * <code>.com.spectralogic.escapepod.cluster.models.URL host = 1;</code>
       */
      public boolean hasHost() {
        return host_ != null;
      }
      /**
       * <code>.com.spectralogic.escapepod.cluster.models.URL host = 1;</code>
       */
      public com.spectralogic.escapepod.cluster.models.Url.URL getHost() {
        return host_ == null ? com.spectralogic.escapepod.cluster.models.Url.URL.getDefaultInstance() : host_;
      }
      /**
       * <code>.com.spectralogic.escapepod.cluster.models.URL host = 1;</code>
       */
      public com.spectralogic.escapepod.cluster.models.Url.URLOrBuilder getHostOrBuilder() {
        return getHost();
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (host_ != null) {
          output.writeMessage(1, getHost());
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (host_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, getHost());
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode)) {
          return super.equals(obj);
        }
        com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode other = (com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode) obj;

        boolean result = true;
        result = result && (hasHost() == other.hasHost());
        if (hasHost()) {
          result = result && getHost()
              .equals(other.getHost());
        }
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasHost()) {
          hash = (37 * hash) + HOST_FIELD_NUMBER;
          hash = (53 * hash) + getHost().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode)
          com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNodeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.spectralogic.escapepod.cluster.models.ClusterConfigProto.internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_ClusterNode_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.spectralogic.escapepod.cluster.models.ClusterConfigProto.internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_ClusterNode_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.class, com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.Builder.class);
        }

        // Construct using com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          if (hostBuilder_ == null) {
            host_ = null;
          } else {
            host_ = null;
            hostBuilder_ = null;
          }
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.spectralogic.escapepod.cluster.models.ClusterConfigProto.internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_ClusterNode_descriptor;
        }

        public com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode getDefaultInstanceForType() {
          return com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.getDefaultInstance();
        }

        public com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode build() {
          com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode buildPartial() {
          com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode result = new com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode(this);
          if (hostBuilder_ == null) {
            result.host_ = host_;
          } else {
            result.host_ = hostBuilder_.build();
          }
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode) {
            return mergeFrom((com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode other) {
          if (other == com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.getDefaultInstance()) return this;
          if (other.hasHost()) {
            mergeHost(other.getHost());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private com.spectralogic.escapepod.cluster.models.Url.URL host_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
            com.spectralogic.escapepod.cluster.models.Url.URL, com.spectralogic.escapepod.cluster.models.Url.URL.Builder, com.spectralogic.escapepod.cluster.models.Url.URLOrBuilder> hostBuilder_;
        /**
         * <code>.com.spectralogic.escapepod.cluster.models.URL host = 1;</code>
         */
        public boolean hasHost() {
          return hostBuilder_ != null || host_ != null;
        }
        /**
         * <code>.com.spectralogic.escapepod.cluster.models.URL host = 1;</code>
         */
        public com.spectralogic.escapepod.cluster.models.Url.URL getHost() {
          if (hostBuilder_ == null) {
            return host_ == null ? com.spectralogic.escapepod.cluster.models.Url.URL.getDefaultInstance() : host_;
          } else {
            return hostBuilder_.getMessage();
          }
        }
        /**
         * <code>.com.spectralogic.escapepod.cluster.models.URL host = 1;</code>
         */
        public Builder setHost(com.spectralogic.escapepod.cluster.models.Url.URL value) {
          if (hostBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            host_ = value;
            onChanged();
          } else {
            hostBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.com.spectralogic.escapepod.cluster.models.URL host = 1;</code>
         */
        public Builder setHost(
            com.spectralogic.escapepod.cluster.models.Url.URL.Builder builderForValue) {
          if (hostBuilder_ == null) {
            host_ = builderForValue.build();
            onChanged();
          } else {
            hostBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.com.spectralogic.escapepod.cluster.models.URL host = 1;</code>
         */
        public Builder mergeHost(com.spectralogic.escapepod.cluster.models.Url.URL value) {
          if (hostBuilder_ == null) {
            if (host_ != null) {
              host_ =
                com.spectralogic.escapepod.cluster.models.Url.URL.newBuilder(host_).mergeFrom(value).buildPartial();
            } else {
              host_ = value;
            }
            onChanged();
          } else {
            hostBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.com.spectralogic.escapepod.cluster.models.URL host = 1;</code>
         */
        public Builder clearHost() {
          if (hostBuilder_ == null) {
            host_ = null;
            onChanged();
          } else {
            host_ = null;
            hostBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.com.spectralogic.escapepod.cluster.models.URL host = 1;</code>
         */
        public com.spectralogic.escapepod.cluster.models.Url.URL.Builder getHostBuilder() {
          
          onChanged();
          return getHostFieldBuilder().getBuilder();
        }
        /**
         * <code>.com.spectralogic.escapepod.cluster.models.URL host = 1;</code>
         */
        public com.spectralogic.escapepod.cluster.models.Url.URLOrBuilder getHostOrBuilder() {
          if (hostBuilder_ != null) {
            return hostBuilder_.getMessageOrBuilder();
          } else {
            return host_ == null ?
                com.spectralogic.escapepod.cluster.models.Url.URL.getDefaultInstance() : host_;
          }
        }
        /**
         * <code>.com.spectralogic.escapepod.cluster.models.URL host = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            com.spectralogic.escapepod.cluster.models.Url.URL, com.spectralogic.escapepod.cluster.models.Url.URL.Builder, com.spectralogic.escapepod.cluster.models.Url.URLOrBuilder> 
            getHostFieldBuilder() {
          if (hostBuilder_ == null) {
            hostBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                com.spectralogic.escapepod.cluster.models.Url.URL, com.spectralogic.escapepod.cluster.models.Url.URL.Builder, com.spectralogic.escapepod.cluster.models.Url.URLOrBuilder>(
                    getHost(),
                    getParentForChildren(),
                    isClean());
            host_ = null;
          }
          return hostBuilder_;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode)
      }

      // @@protoc_insertion_point(class_scope:com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode)
      private static final com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode();
      }

      public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<ClusterNode>
          PARSER = new com.google.protobuf.AbstractParser<ClusterNode>() {
        public ClusterNode parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new ClusterNode(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<ClusterNode> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ClusterNode> getParserForType() {
        return PARSER;
      }

      public com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object nodeId_;
    /**
     * <code>string nodeId = 2;</code>
     */
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeId_ = s;
        return s;
      }
    }
    /**
     * <code>string nodeId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODES_FIELD_NUMBER = 3;
    private java.util.List<com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode> nodes_;
    /**
     * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
     */
    public java.util.List<com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode> getNodesList() {
      return nodes_;
    }
    /**
     * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
     */
    public java.util.List<? extends com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNodeOrBuilder> 
        getNodesOrBuilderList() {
      return nodes_;
    }
    /**
     * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
     */
    public int getNodesCount() {
      return nodes_.size();
    }
    /**
     * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
     */
    public com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode getNodes(int index) {
      return nodes_.get(index);
    }
    /**
     * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
     */
    public com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNodeOrBuilder getNodesOrBuilder(
        int index) {
      return nodes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getNodeIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nodeId_);
      }
      for (int i = 0; i < nodes_.size(); i++) {
        output.writeMessage(3, nodes_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getNodeIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nodeId_);
      }
      for (int i = 0; i < nodes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, nodes_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig)) {
        return super.equals(obj);
      }
      com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig other = (com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getNodeId()
          .equals(other.getNodeId());
      result = result && getNodesList()
          .equals(other.getNodesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + NODEID_FIELD_NUMBER;
      hash = (53 * hash) + getNodeId().hashCode();
      if (getNodesCount() > 0) {
        hash = (37 * hash) + NODES_FIELD_NUMBER;
        hash = (53 * hash) + getNodesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.spectralogic.escapepod.cluster.models.ClusterConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.spectralogic.escapepod.cluster.models.ClusterConfig)
        com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.spectralogic.escapepod.cluster.models.ClusterConfigProto.internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.spectralogic.escapepod.cluster.models.ClusterConfigProto.internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.class, com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.Builder.class);
      }

      // Construct using com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        nodeId_ = "";

        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spectralogic.escapepod.cluster.models.ClusterConfigProto.internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_descriptor;
      }

      public com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig getDefaultInstanceForType() {
        return com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.getDefaultInstance();
      }

      public com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig build() {
        com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig buildPartial() {
        com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig result = new com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        result.nodeId_ = nodeId_;
        if (nodesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            nodes_ = java.util.Collections.unmodifiableList(nodes_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.nodes_ = nodes_;
        } else {
          result.nodes_ = nodesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig) {
          return mergeFrom((com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig other) {
        if (other == com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getNodeId().isEmpty()) {
          nodeId_ = other.nodeId_;
          onChanged();
        }
        if (nodesBuilder_ == null) {
          if (!other.nodes_.isEmpty()) {
            if (nodes_.isEmpty()) {
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureNodesIsMutable();
              nodes_.addAll(other.nodes_);
            }
            onChanged();
          }
        } else {
          if (!other.nodes_.isEmpty()) {
            if (nodesBuilder_.isEmpty()) {
              nodesBuilder_.dispose();
              nodesBuilder_ = null;
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000004);
              nodesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodesFieldBuilder() : null;
            } else {
              nodesBuilder_.addAllMessages(other.nodes_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nodeId_ = "";
      /**
       * <code>string nodeId = 2;</code>
       */
      public java.lang.String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nodeId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNodeIdBytes() {
        java.lang.Object ref = nodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nodeId = 2;</code>
       */
      public Builder setNodeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nodeId = 2;</code>
       */
      public Builder clearNodeId() {
        
        nodeId_ = getDefaultInstance().getNodeId();
        onChanged();
        return this;
      }
      /**
       * <code>string nodeId = 2;</code>
       */
      public Builder setNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nodeId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode> nodes_ =
        java.util.Collections.emptyList();
      private void ensureNodesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          nodes_ = new java.util.ArrayList<com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode>(nodes_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode, com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.Builder, com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNodeOrBuilder> nodesBuilder_;

      /**
       * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
       */
      public java.util.List<com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode> getNodesList() {
        if (nodesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodes_);
        } else {
          return nodesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
       */
      public int getNodesCount() {
        if (nodesBuilder_ == null) {
          return nodes_.size();
        } else {
          return nodesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
       */
      public com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode getNodes(int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);
        } else {
          return nodesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
       */
      public Builder setNodes(
          int index, com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.set(index, value);
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
       */
      public Builder setNodes(
          int index, com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
       */
      public Builder addNodes(com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
       */
      public Builder addNodes(
          int index, com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(index, value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
       */
      public Builder addNodes(
          com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
       */
      public Builder addNodes(
          int index, com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
       */
      public Builder addAllNodes(
          java.lang.Iterable<? extends com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode> values) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodes_);
          onChanged();
        } else {
          nodesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
       */
      public Builder clearNodes() {
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
       */
      public Builder removeNodes(int index) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.remove(index);
          onChanged();
        } else {
          nodesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
       */
      public com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.Builder getNodesBuilder(
          int index) {
        return getNodesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
       */
      public com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNodeOrBuilder getNodesOrBuilder(
          int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);  } else {
          return nodesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
       */
      public java.util.List<? extends com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNodeOrBuilder> 
           getNodesOrBuilderList() {
        if (nodesBuilder_ != null) {
          return nodesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodes_);
        }
      }
      /**
       * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
       */
      public com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.Builder addNodesBuilder() {
        return getNodesFieldBuilder().addBuilder(
            com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.getDefaultInstance());
      }
      /**
       * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
       */
      public com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.Builder addNodesBuilder(
          int index) {
        return getNodesFieldBuilder().addBuilder(
            index, com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.getDefaultInstance());
      }
      /**
       * <code>repeated .com.spectralogic.escapepod.cluster.models.ClusterConfig.ClusterNode nodes = 3;</code>
       */
      public java.util.List<com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.Builder> 
           getNodesBuilderList() {
        return getNodesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode, com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.Builder, com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNodeOrBuilder> 
          getNodesFieldBuilder() {
        if (nodesBuilder_ == null) {
          nodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode, com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNode.Builder, com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig.ClusterNodeOrBuilder>(
                  nodes_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          nodes_ = null;
        }
        return nodesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.spectralogic.escapepod.cluster.models.ClusterConfig)
    }

    // @@protoc_insertion_point(class_scope:com.spectralogic.escapepod.cluster.models.ClusterConfig)
    private static final com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig();
    }

    public static com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClusterConfig>
        PARSER = new com.google.protobuf.AbstractParser<ClusterConfig>() {
      public ClusterConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ClusterConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClusterConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClusterConfig> getParserForType() {
      return PARSER;
    }

    public com.spectralogic.escapepod.cluster.models.ClusterConfigProto.ClusterConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_ClusterNode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_ClusterNode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ClusterConfig.proto\022)com.spectralogic." +
      "escapepod.cluster.models\032\tUrl.proto\"\317\001\n\r" +
      "ClusterConfig\022\014\n\004name\030\001 \001(\t\022\016\n\006nodeId\030\002 " +
      "\001(\t\022S\n\005nodes\030\003 \003(\0132D.com.spectralogic.es" +
      "capepod.cluster.models.ClusterConfig.Clu" +
      "sterNode\032K\n\013ClusterNode\022<\n\004host\030\001 \001(\0132.." +
      "com.spectralogic.escapepod.cluster.model" +
      "s.URLB?\n)com.spectralogic.escapepod.clus" +
      "ter.modelsB\022ClusterConfigProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.spectralogic.escapepod.cluster.models.Url.getDescriptor(),
        }, assigner);
    internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_descriptor,
        new java.lang.String[] { "Name", "NodeId", "Nodes", });
    internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_ClusterNode_descriptor =
      internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_descriptor.getNestedTypes().get(0);
    internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_ClusterNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_spectralogic_escapepod_cluster_models_ClusterConfig_ClusterNode_descriptor,
        new java.lang.String[] { "Host", });
    com.spectralogic.escapepod.cluster.models.Url.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
